//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./suggestion_types');
//HELPER FUNCTIONS AND STRUCTURES

SuggestionService_findSuggestionsFor_args = function(args) {
  this.index = null;
  this.query = null;
  this.k = null;
  if (args) {
    if (args.index !== undefined) {
      this.index = args.index;
    }
    if (args.query !== undefined) {
      this.query = args.query;
    }
    if (args.k !== undefined) {
      this.k = args.k;
    }
  }
};
SuggestionService_findSuggestionsFor_args.prototype = {};
SuggestionService_findSuggestionsFor_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.index = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.query = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I16) {
        this.k = input.readI16();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SuggestionService_findSuggestionsFor_args.prototype.write = function(output) {
  output.writeStructBegin('SuggestionService_findSuggestionsFor_args');
  if (this.index !== null && this.index !== undefined) {
    output.writeFieldBegin('index', Thrift.Type.STRING, 1);
    output.writeString(this.index);
    output.writeFieldEnd();
  }
  if (this.query !== null && this.query !== undefined) {
    output.writeFieldBegin('query', Thrift.Type.STRING, 2);
    output.writeString(this.query);
    output.writeFieldEnd();
  }
  if (this.k !== null && this.k !== undefined) {
    output.writeFieldBegin('k', Thrift.Type.I16, 3);
    output.writeI16(this.k);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SuggestionService_findSuggestionsFor_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
SuggestionService_findSuggestionsFor_result.prototype = {};
SuggestionService_findSuggestionsFor_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.Suggestion();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SuggestionService_findSuggestionsFor_result.prototype.write = function(output) {
  output.writeStructBegin('SuggestionService_findSuggestionsFor_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SuggestionServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
SuggestionServiceClient.prototype = {};
SuggestionServiceClient.prototype.findSuggestionsFor = function(index, query, k, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_findSuggestionsFor(index, query, k);
};

SuggestionServiceClient.prototype.send_findSuggestionsFor = function(index, query, k) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('findSuggestionsFor', Thrift.MessageType.CALL, this.seqid);
  var args = new SuggestionService_findSuggestionsFor_args();
  args.index = index;
  args.query = query;
  args.k = k;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SuggestionServiceClient.prototype.recv_findSuggestionsFor = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SuggestionService_findSuggestionsFor_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('findSuggestionsFor failed: unknown result');
};
SuggestionServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
SuggestionServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

SuggestionServiceProcessor.prototype.process_findSuggestionsFor = function(seqid, input, output) {
  var args = new SuggestionService_findSuggestionsFor_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.findSuggestionsFor(args.index, args.query, args.k, function (err, result) {
    var result = new SuggestionService_findSuggestionsFor_result((err != null ? err : {success: result}));
    output.writeMessageBegin("findSuggestionsFor", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

